name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Update README.md
        run: |
          python build.py

      - name: Commit new README.md file
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md from GitHub Actions"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
