name: Main

on:
  workflow_dispatch: 
  push: 
  schedule:
    - cron: '0 12 * * 1'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0


      - name: Lint code base
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Update README.md
        run: |
          python build.py

      - name: Commit new README.md file
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md from GitHub Actions"
          git push --all -f "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
