name: Main

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * 1'

permissions: {}

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Load super-linter configuration
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint code base
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    permissions: 
      contents: write 

    steps:
      - name: Get the code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Update README.md
        run: |
          python build.py

      - name: Commit new README.md file
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md from GitHub Actions"
          git push --all -f
