name: README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Update README.md
        run: |
          python3 -m pip install -U pip
          python3 -m pip install setuptools wheel
          python3 -m pip install -r requirements.txt
          python3 build.py
      - name: Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md from GitHub action"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
